moontag_app/urls.py
from django.urls import path,include
from moontag_app import views
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('',views.home,name='home'),
    path('register1',views.register1,name='register1'),
    path('login1',views.login1,name='login1'),
    path('logout1',views.logout1,name='log_out1'),
    path('activate/<uidb64>/<token>',views.activate,name='activate'),
    path('categories',views.categories,name='categories'),
    path('brands',views.brands,name='brands'),
    path('product-list',views.product_list,name='product-list'),
    path('category-product-list/<int:cat_id>',views.category_product_list,name='category-product-list'),
    path('brand-product-list/<int:brand_id>',views.brand_product_list,name='brand-product-list'),
    path('product/<str:slug>/<int:id>',views.product_page,name='product_page'),
    path('search-result',views.search_result,name='search_result'),
    path('filter-data',views.filter_data,name='filter_data'),
    path('add-to-cart',views.add_to_cart,name='add_to_cart'),
    path('cart',views.cart_page,name='cart'),
    path('delete-from-cart',views.delete_cart_item,name='delete_cart_item'),
    path('update-cart',views.update_cart_item,name='update-cart'),
    path('checkout',views.checkout,name='checkout'),
    path('paypal/', include('paypal.standard.ipn.urls')),
    path('payment-done/', views.payment_done, name='payment_done'),
    path('payment-cancelled/', views.payment_canceled, name='payment_cancelled'),
    path('add-product',views.add_product,name='add_product'),
    path('add-category',views.add_category,name='add_category'),
    path('add-brand',views.add_brand,name='add_brand'),
    path('add-color',views.add_color,name='add_color'),
    path('add-size',views.add_size,name='add_size'),
    path('add-banner',views.add_banner,name='add_banner'),
    path('user-dashboard',views.user_dashboard,name='user_dashboard'),
    path('user-orders',views.user_orders,name='user_orders'),
    path('user-orders-items/<int:id>',views.user_orders_items,name='user_orders_items'),
    path('add-attribute',views.add_attribute,name='add_attribute'),
    path('order-search',views.order_search,name='order_search'),
    path('checkout-purchasing',views.checkout_purchasing,name='checkout_purchasing'),
    path('display-product',views.display_product,name='display_product'),
    path('data',views.data,name='data'),
    path('add-wishlist',views.add_wishlist,name='add_wishlist'),
    path('wishlist',views.wishlist,name='wishlist'),
    path('store-register',views.store_register,name='store_register'),
    path('welcome',views.welcome,name='welcome'),
    path('store',views.store,name='store'),
    path('store/add-product',views.vendor_add_product,name='vendor_add_product'),
    path('store/add-attribute',views.vendor_add_attribute,name='vendor_add_attribute'),
    path('store/todo/delete',views.delete_todo,name='delete_todo'),
    path('store/order/<int:id>',views.order_details,name='order_details'),
    path('store/products',views.store_products,name='store_products'),
    path('store/products/edit/<int:id>',views.vendor_edit_product,name='vendor_edit_product'),
    path('store/withraw',views.withraw,name='withraw'),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

moontag_project/urls.py
from django.contrib import admin
from django.urls import path , include




urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('moontag_app.urls'))
]

moontag_app/models.py
from django.db import models
from django.utils.html import mark_safe # send safely into django data and can put photos to the App in the admin panel
from django.contrib.auth.models import User

# Create your models here.
class Category(models.Model):
    title = models.CharField(max_length=100)
    img = models.ImageField(upload_to='media/category_images')

    class Meta:
        verbose_name_plural = '1. Categories'

    def image_tag(self):
        return mark_safe('<img src="%s" width="60" height="60" />' % (self.img.url))

    def __str__(self):
        return self.title


class Brand(models.Model):
    title = models.CharField(max_length=100)
    img = models.ImageField(upload_to='media/brand_images')

    class Meta:
        verbose_name_plural = '2. Brands'

    def __str__(self):
        return self.title


class Color(models.Model):
    title = models.CharField(max_length=100)
    color_code = models.CharField(max_length=100)

    class Meta:
        verbose_name_plural = '3. Colors'

    def color_tag(self):
        return mark_safe('<div style="width:30px; height:30px; background-color:%s"></div>' % (self.color_code))

    def __str__(self):
        return self.title


class Size(models.Model):
    title = models.CharField(max_length=100)

    class Meta:
        verbose_name_plural = '4. Sizes'

    def __str__(self):
        return self.title


class Product(models.Model):
    title = models.CharField(max_length=200)
    slug = models.CharField(max_length=400)
    detail = models.TextField()
    specs = models.TextField()
    category = models.ForeignKey(Category,on_delete=models.CASCADE)
    brand = models.ForeignKey(Brand,on_delete=models.CASCADE)
    color = models.ForeignKey(Color,on_delete=models.CASCADE)
    size = models.ForeignKey(Size,on_delete=models.CASCADE)
    status = models.BooleanField(default=True)
    is_featured = models.BooleanField(default=False)


    class Meta:
        verbose_name_plural = '5. Products'

    def __str__(self):
        return self.title

class Banner(models.Model):
    img = models.ImageField(upload_to='media/banner_images')
    text = models.CharField(max_length=300)

    def image_tag(self):
        return mark_safe('<img src="%s" width="90"/>' % (self.img.url))

    def __str__(self):
        return self.text

    class Meta:
        verbose_name_plural = '6. Banners'

class ProductAttribute(models.Model):
    product = models.ForeignKey(Product,on_delete=models.CASCADE)
    color = models.ForeignKey(Color,on_delete=models.CASCADE)
    size = models.ForeignKey(Size,on_delete=models.CASCADE)
    price = models.PositiveBigIntegerField()
    img = models.ImageField(upload_to="media/product_images",null=True)
    
    class Meta:
        verbose_name_plural = '7. Product Attribute'

    def __str__ (self):
        return self.product.title 

    def image_tag(self):
        return mark_safe('<img src="%s" width="60" height="60" />' % (self.img.url))


class CartOrder(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    total_amt = models.FloatField()
    paid_status = models.BooleanField(default=False)
    order_dt = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = '8. Cart order'

class CartOrderItems(models.Model):
    order = models.ForeignKey(CartOrder,on_delete=models.CASCADE)
    in_num = models.CharField(max_length=150)
    item = models.CharField(max_length=150)
    img = models.CharField(max_length=200)
    qty = models.IntegerField()
    price = models.FloatField()
    total = models.FloatField() # save according the price and qty

    class Meta:
        verbose_name_plural = '9. Cart order items'

    def image_tag(self):
        return mark_safe('<img src="/media/%s" width="60" height="60" />' % (self.img))


RATING = (
    (1,'1'),
    (2,'2'),
    (3,'3'),
    (4,'4'),
    (5,'5'),
)

class ProductReview(models.Model):
    user = models.CharField(max_length=100,editable=False)
    product = models.CharField(max_length=100,editable=False)
    review_text = models.TextField()
    review_rating = models.CharField(choices=RATING, max_length=150)
    
    class Meta:
        verbose_name_plural = 'A10. Product Review'


class Wishlist(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    product = models.ForeignKey(Product,on_delete=models.CASCADE)

    class Meta:
        verbose_name_plural = 'A11. Wishlist'

class Vendors(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    store_name = models.CharField(max_length=100)
    company_name = models.CharField(max_length=100)
    store_img = models.ImageField(upload_to="media/store_images",null=True)
    business_email = models.EmailField(max_length=254)
    pay_pal = models.EmailField(max_length=254)

    class Meta:
        verbose_name_plural = 'A12. Vendors'

    def image_tag(self):
        return mark_safe('<img src="/media/%s" width="60" height="60" />' % (self.img))


class VendorAddProduct(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    product = models.ForeignKey(Product,on_delete=models.CASCADE)

    class Meta:
        verbose_name_plural = 'A13. Vendors Products'


class Todo(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    todo = models.CharField(max_length=200)

    class Meta:
        verbose_name_plural = 'A14. Todo'


class Withraw(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    amount = models.FloatField()

    class Meta:
        verbose_name_plural = 'A15. Withraw'

moontag_project/templates/marketplace/edit_product.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>Admin Panel</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="" name="keywords">
    <meta content="" name="description">

    <!-- Favicon -->
    <link href="img/favicon.ico" rel="icon">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;600&family=Roboto:wght@500;700&display=swap" rel="stylesheet"> 
    
    <!-- Icon Font Stylesheet -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link rel="stylesheet" type="text/css" href="{% static 'cssM/owl.carousel.min.css' %}" />
    <link href="{% static 'cssM/tempusdominus-bootstrap-4.min.css' %}" rel="stylesheet" />

    <!-- Customized Bootstrap Stylesheet -->
    <link href="{% static 'cssM/css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Template Stylesheet -->
    <link href="{% static 'cssM/css/style.css' %}" rel="stylesheet">
</head>

<body>
    <div class="container-fluid position-relative d-flex p-0">
        <!-- Spinner Start -->
        <div id="spinner" class="show bg-dark position-fixed translate-middle w-100 vh-100 top-50 start-50 d-flex align-items-center justify-content-center">
            <div class="spinner-border text-primary" style="width: 3rem; height: 3rem;" role="status">
                <span class="sr-only">Loading...</span>
            </div>
        </div>
        <!-- Spinner End -->
        <!-- Content Start -->
        <div class="content">
            {% for message in messages %}
            <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
                <strong>Message:</strong> {{ message }}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
            </button>
            </div>
            {% endfor %}

            <!-- Form Start -->
            <div class="container-fluid pt-4 px-4">
                <div class="row g-4">
                    <div class="col-sm-12 col-xl-6">
                        <div class="bg-secondary rounded h-100 p-4">      
                            <h6 class="mb-4">Edit Product</h6>
                            <form action="/store/products/edit/{{product.id}}" method="post">
                                {% csrf_token %}
                                <div class="mb-3">
                                    <label class="form-label">Product Title</label>
                                    <input type="text" class="form-control" id="exampleInputEmail1" name="title" placeholder="{{product.title}}">
                                    <div>
                                    </div>
                                </div>
                                <div class="mb-3">
                                    <label class="form-label">Product Slug</label>
                                    <input type="text" class="form-control" id="exampleInputEmail1" name="slug"  placeholder="{{product.slug}}">
                                    <div>
                                    </div>
                                </div>
                                <div class="form-floating">
                                    <textarea class="form-control" name="detail" placeholder="Product detail"
                                        id="floatingTextarea" style="height: 150px;"></textarea>
                                    <label for="floatingTextarea">Product Detail</label>
                                </div>
                                <br>
                                <div class="form-floating">
                                    <textarea class="form-control" name="specs" placeholder="Product specs"
                                        id="floatingTextarea" style="height: 120px;"></textarea>
                                    <label for="floatingTextarea">Product Specs</label>
                                </div>
                                <br>       
                                <button type="submit" class="btn btn-primary">Save Changes</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
            <!-- Form End -->


            <!-- Footer Start -->
            <div class="container-fluid pt-4 px-4">
                <div class="bg-secondary rounded-top p-4">
                    <div class="row">
                        <div class="col-12 col-sm-6 text-center text-sm-start">
                            &copy; <a href="/store">Monntag</a>, All Right Reserved. 
                        </div>
                    </div>
                </div>
            </div>
            <!-- Footer End -->
        </div>
        <!-- Content End -->


        <!-- Back to Top -->
        <a href="#" class="btn btn-lg btn-primary btn-lg-square back-to-top"><i class="bi bi-arrow-up"></i></a>
    </div>

    <!-- JavaScript Libraries -->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="{% static '/jsM/js/chart.min.js' %}"></script>
    <script src="{% static '/jsM/js/easing.min.js' %}"></script>
    <script src="{% static '/jsM/js/waypoints.min.js' %}"></script>
    <script src="{% static '/jsM/js/owl.carousel.min.js' %}"></script>
    <script src="{% static '/jsM/js/moment.min.js' %}"></script>
    <script src="{% static '/jsM/js/moment-timezone.min.js' %}"></script>
    <script src="{% static '/jsM/js/tempusdominus-bootstrap-4.min.js' %}"></script>
    <!-- Template Javascript -->
    <script src="{% static '/jsM/main.js' %}"></script>
</body>

</html>

moontag_project/templates/marketplace/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>Admin Panel</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="" name="keywords">
    <meta content="" name="description">

    <!-- Favicon -->
    <link href="img/favicon.ico" rel="icon">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;600&family=Roboto:wght@500;700&display=swap" rel="stylesheet"> 
    
    <!-- Icon Font Stylesheet -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link rel="stylesheet" type="text/css" href="{% static 'cssM/owl.carousel.min.css' %}" />
    <link href="{% static 'cssM/tempusdominus-bootstrap-4.min.css' %}" rel="stylesheet" />

    <!-- Customized Bootstrap Stylesheet -->
    <link href="{% static 'cssM/css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Template Stylesheet -->
    <link href="{% static 'cssM/css/style.css' %}" rel="stylesheet">
</head>

<body>
    <div class="container-fluid position-relative d-flex p-0">
        <!-- Spinner Start -->
        <div id="spinner" class="show bg-dark position-fixed translate-middle w-100 vh-100 top-50 start-50 d-flex align-items-center justify-content-center">
            <div class="spinner-border text-primary" style="width: 3rem; height: 3rem;" role="status">
                <span class="sr-only">Loading...</span>
            </div>
        </div>
        <!-- Spinner End -->
        <!-- Sidebar Start -->
        <div class="sidebar pe-4 pb-3">
            <nav class="navbar bg-secondary navbar-dark">
                <a href="/store" class="navbar-brand mx-4 mb-3">
                    <h3 class="text-primary"><i class="fa fa-user-edit me-2"></i>Moontag</h3>
                </a>
                <div class="d-flex align-items-center ms-4 mb-4">
                    <div class="position-relative">
                        <img class="rounded-circle" src="media/{{vendor.store_img}}" alt="" style="width: 40px; height: 40px;">
                        <div class="bg-success rounded-circle border border-2 border-white position-absolute end-0 bottom-0 p-1"></div>
                    </div>
                    <div class="ms-3">
                        <h6 class="mb-0">{{user}}</h6>
                        <span>Admin</span>
                    </div>
                </div>
                <div class="navbar-nav w-100">
                    <a href="/store" class="nav-item nav-link active"><i class="fa fa-tachometer-alt me-2"></i>Dashboard</a>
                    <a href="/store/add-product" class="nav-item nav-link"><i class="fab fa-product-hunt"></i> Add Product</a>
                    <a href="/store/add-attribute" class="nav-item nav-link"><i class="fa fa-window-restore"></i> Add Attribute</a>
                    <a href="/store/products" class="nav-item nav-link"><i class="fa fa-table me-2"></i>Products</a>
                    <a href="/store/withraw" class="nav-item nav-link"><i class="fa fa-chart-bar me-2"></i>Withraw</a>
                </div>
            </nav>
        </div>
        <!-- Sidebar End -->


        <!-- Content Start -->
        <div class="content">
            <!-- Navbar Start -->
            <nav class="navbar navbar-expand bg-secondary navbar-dark sticky-top px-4 py-0">
                <a href="/store" class="navbar-brand d-flex d-lg-none me-4">
                    <h2 class="text-primary mb-0"><i class="fa fa-user-edit"></i></h2>
                </a>
                <a href="#" class="sidebar-toggler flex-shrink-0">
                    <i class="fa fa-bars"></i>
                </a>
                <div class="navbar-nav align-items-center ms-auto">
                    <div class="nav-item dropdown">
                        <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">
                            <img class="rounded-circle me-lg-2" src="media/{{vendor.store_img}}" alt="" style="width: 40px; height: 40px;">
                            <span class="d-none d-lg-inline-flex">{{user}}</span>
                        </a>
                        <div class="dropdown-menu dropdown-menu-end bg-secondary border-0 rounded-0 rounded-bottom m-0">
                            <a href="/logout1" class="dropdown-item">Log Out</a>
                        </div>
                    </div>
                </div>
            </nav>
            <!-- Navbar End -->


            <!-- Sale & Revenue Start -->
            <div class="container-fluid pt-4 px-4">
                <div class="row g-4">
                    <div class="col-sm-6 col-xl-3">
                        <div class="bg-secondary rounded d-flex align-items-center justify-content-between p-4">
                            <i class="fa fa-chart-line fa-3x text-primary"></i>
                            <div class="ms-3">
                                <p class="mb-2">Total Sale</p>
                                <h6 class="mb-0">${{total_sales}}</h6>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-6 col-xl-3">
                        <div class="bg-secondary rounded d-flex align-items-center justify-content-between p-4">
                            <i class="fa fa-chart-pie fa-3x text-primary"></i>
                            <div class="ms-3">
                                <p class="mb-2">Profit after our 17% commission </p>
                                <h6 class="mb-0">${{commission}}</h6>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- Sale & Revenue End -->
            <!-- Recent Sales Start -->
            <div class="container-fluid pt-4 px-4">
                <div class="bg-secondary text-center rounded p-4">
                    <div class="d-flex align-items-center justify-content-between mb-4">
                        <h6 class="mb-0">Recent Salse</h6>
                    </div>
                    <div class="table-responsive">
                        <table class="table text-start align-middle table-bordered table-hover mb-0">
                            <thead>
                                <tr class="text-white">
                                    <th>User</th>
                                    <th>Total Amount</th>
                                    <th>Paid Status *You can see only Paid Orders</th>
                                    <th>Order Time</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for order in orders %}
                                <tr>
                                    <td>{{order.user}}</td>
                                    <td>{{order.total_amt}}</td>
                                    <td>{{order.paid_status}}</td>
                                    <td>{{order.order_dt}}</td>
                                    <td><button type="button" class="btn btn-sm btn-primary"><a style="color: white;" href="/store/order/{{order.id}}">Detail</a></button></td>
                                    </form>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            <!-- Recent Sales End -->


            <!-- Widgets Start -->
            <div class="container-fluid pt-4 px-4">
                <div class="row g-4">
                    <div class="col-sm-12 col-md-6 col-xl-4">
                        <div class="h-100 bg-secondary rounded p-4">
                            <div class="d-flex align-items-center justify-content-between mb-2">
                                <h6 class="mb-0">Products</h6>
                                <a href="/store/products">Show All</a>
                            </div>
                            {% for product in vendor_products %}
                            <div class="d-flex align-items-center border-bottom py-3">
                                <img class="rounded-circle flex-shrink-0" src="/media/{{product.product.productattribute_set.first.img}}" alt="" style="width: 40px; height: 40px;">
                                <div class="w-100 ms-3">          
                                    <div class="d-flex w-100 justify-content-between">
                                        <h6 class="mb-0">{{product.product.title}}</h6>
                                        <small>Category: <a href="/category-product-list/{{product.product.category.id}}">{{product.product.category}}</a></small>
                                    </div>
                                    <span>{{product.product.detail}}</span>
                                </div>
                            </div>
                            {% endfor %}
                        </div>
                    </div>
                    <div class="col-sm-12 col-md-6 col-xl-4">
                        <div class="h-100 bg-secondary rounded p-4">
                            <div class="d-flex align-items-center justify-content-between mb-4">
                                <h6 class="mb-0">Calender</h6>
                            </div>
                            <div id="calender"></div>
                        </div>
                    </div>
                    <div class="col-sm-12 col-md-6 col-xl-4">
                        <div class="h-100 bg-secondary rounded p-4">
                            <div class="d-flex align-items-center justify-content-between mb-4">
                                <h6 class="mb-0">To Do List</h6>
                            </div>
                            <form action="/store" method="post">
                                {% csrf_token %}
                            <div class="d-flex mb-2">
                                <input class="form-control bg-dark border-0" type="text" placeholder="Enter task" name="todo">
                                <button type="submit" class="btn btn-primary ms-2">Add</button>
                            </div>
                            </form>
                            {% for todo in todos %}
                            <div class="d-flex align-items-center border-bottom py-2">
                                <div class="w-100 ms-3">
                                    <div class="d-flex w-100 align-items-center justify-content-between">
                                        <span>{{todo.todo}}</span>
                                        <form action="/store/todo/delete" method="post">
                                            {% csrf_token %}
                                            <input type="hidden" name="todoId" value="{{todo.id}}">
                                            <button class="btn btn-sm"><i class="fa fa-times"></i></button>
                                        </form>
                                    </div>
                                </div>
                            </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
            <!-- Widgets End -->


            <!-- Footer Start -->
            <div class="container-fluid pt-4 px-4">
                <div class="bg-secondary rounded-top p-4">
                    <div class="row">
                        <div class="col-12 col-sm-6 text-center text-sm-start">
                            &copy; <a href="/store">Monntag</a>, All Right Reserved. 
                        </div>
                    </div>
                </div>
            </div>
            <!-- Footer End -->
        </div>
        <!-- Content End -->


        <!-- Back to Top -->
        <a href="#" class="btn btn-lg btn-primary btn-lg-square back-to-top"><i class="bi bi-arrow-up"></i></a>
    </div>

    <!-- JavaScript Libraries -->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="{% static '/jsM/js/chart.min.js' %}"></script>
    <script src="{% static '/jsM/js/easing.min.js' %}"></script>
    <script src="{% static '/jsM/js/waypoints.min.js' %}"></script>
    <script src="{% static '/jsM/js/owl.carousel.min.js' %}"></script>
    <script src="{% static '/jsM/js/moment.min.js' %}"></script>
    <script src="{% static '/jsM/js/moment-timezone.min.js' %}"></script>
    <script src="{% static '/jsM/js/tempusdominus-bootstrap-4.min.js' %}"></script>
    <!-- Template Javascript -->
    <script src="{% static '/jsM/main.js' %}"></script>
</body>

</html>

moontag_project/templates/marketplace/store_register.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<!DOCTYPE html>
{% for message in messages %}
<div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
    <strong>Message:</strong> {{ message }}
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
<span aria-hidden="true">&times;</span>
</button>
</div>
{% endfor %}
<form action="/store-register" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <label>Store Name</label>
    <input type="text" name="storeName" id="storeName" class="form-control">
    <br>
    <label>Company Name</label>
    <input type="text" name="companyName" id="companyName" class="form-control">
    <br>
    <label>Store Image</label>
    <input type="file" name="storeImage" id="storeImage" accept="image/*" class="form-control-file">
    <br>
    <label>bussiness Email</label>
    <input type="email" name="businessEmail" id="bemail" class="form-control">
    <br>
    <label>Pay Pal Email For Payout</label>
    <input type="text" name="payPalEmail" id="pemail" class="form-control">
    <br>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>
{% endblock %}

moontag_project/templates/marketplace/welcome.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<!DOCTYPE html>
<h1>Hello {{user}}</h1>
<a href="/store-register" >Register Your Store</a>
{% endblock %}